use tauri::Manager;
mod commands;
use commands::license::{get_machine_hash, store_secure, get_secure, delete_secure};
// Include the code generated by build.rs
include!(concat!(env!("OUT_DIR"), "/migrations.rs"));

#[tauri::command]
fn greet(name: &str) -> String {
    format!("Hello, {}! You've been greeted from Rust!", name)
}

#[tauri::command]
fn set_window_theme(app_handle: tauri::AppHandle, theme: String) {
    let window = app_handle.get_webview_window("main").unwrap();

    if theme == "dark" {
        window.set_decorations(true).unwrap();
        window.set_theme(Some(tauri::Theme::Dark)).unwrap();
    } else {
        window.set_decorations(true).unwrap();
        window.set_theme(Some(tauri::Theme::Light)).unwrap();
    }
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    // 1. Initial System Migration
    let mut migrations = vec![
        tauri_plugin_sql::Migration {
            version: 1,
            description: "system_init",
            sql: "CREATE TABLE IF NOT EXISTS app_system_info (key TEXT PRIMARY KEY, value TEXT);",
            kind: tauri_plugin_sql::MigrationKind::Up,
        },
    ];

    // 2. Append Drizzle migrations with the +1 offset
    for mut m in get_migrations() {
        m.version += 1; 
        migrations.push(m);
    }

    // 3. Add the Inventory Triggers as the FINAL migration
    // This ensures they are created after the Drizzle tables exist.
    let last_version = migrations.last().map(|m| m.version).unwrap_or(1);
    
    migrations.push(tauri_plugin_sql::Migration {
        version: last_version + 1,
        description: "inventory_stock_triggers",
        sql: "
            CREATE TRIGGER IF NOT EXISTS trg_sale_items_stock_decrement
            AFTER INSERT ON sale_items
            BEGIN
                UPDATE products 
                SET current_stock = current_stock - NEW.quantity
                WHERE uuid = NEW.product_id AND NEW.variant_id IS NULL;

                UPDATE product_variants 
                SET current_stock = current_stock - NEW.quantity
                WHERE uuid = NEW.variant_id;
            END;

            CREATE TRIGGER IF NOT EXISTS trg_sale_items_stock_sync
            AFTER UPDATE OF quantity ON sale_items
            BEGIN
                UPDATE products 
                SET current_stock = current_stock - (NEW.quantity - OLD.quantity)
                WHERE uuid = NEW.product_id AND NEW.variant_id IS NULL;

                UPDATE product_variants 
                SET current_stock = current_stock - (NEW.quantity - OLD.quantity)
                WHERE uuid = NEW.variant_id;
            END;

            CREATE TRIGGER IF NOT EXISTS trg_sale_items_stock_increment
            AFTER DELETE ON sale_items
            BEGIN
                UPDATE products 
                SET current_stock = current_stock + OLD.quantity
                WHERE uuid = OLD.product_id AND OLD.variant_id IS NULL;

                UPDATE product_variants 
                SET current_stock = current_stock + OLD.quantity
                WHERE uuid = OLD.variant_id;
            END;
        ",
        kind: tauri_plugin_sql::MigrationKind::Up,
    });

    tauri::Builder::default()
        .plugin(
            tauri_plugin_sql::Builder::default()
                .add_migrations("sqlite:local.db", migrations)
                .build(),
        )
        .plugin(tauri_plugin_opener::init())
        .plugin(tauri_plugin_notification::init())
        .plugin(tauri_plugin_os::init())
        .plugin(tauri_plugin_process::init())
        .plugin(tauri_plugin_updater::Builder::new().build())
        .plugin(tauri_plugin_store::Builder::default().build())
        .setup(|app| {
            let app_data_dir = app.path().app_data_dir().expect("failed to get app data dir");
            
            if !app_data_dir.exists() {
                std::fs::create_dir_all(&app_data_dir).expect("failed to create app data dir");
            }

            println!("Database path: {:?}", app_data_dir.join("local.db"));

            let window = app.get_webview_window("main").unwrap();
            window.set_theme(Some(tauri::Theme::Light)).unwrap();

            Ok(())
        })
        .invoke_handler(tauri::generate_handler![greet, set_window_theme, get_machine_hash,
            store_secure,
            get_secure,
            delete_secure])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}