use tauri::Manager;
mod commands;
use commands::license::{get_machine_hash, store_secure, get_secure, delete_secure};
mod sync_engine;
mod sync_commands;
use sync_engine::SyncEngine;
use sync_commands::{sync_all, sync_table, get_unsynced_counts, SyncEngineState};
use sqlx::SqlitePool;
use std::sync::Arc;
use tokio::sync::Mutex;
// Include the code generated by build.rs
include!(concat!(env!("OUT_DIR"), "/migrations.rs"));

#[tauri::command]
fn greet(name: &str) -> String {
    format!("Hello, {}! You've been greeted from Rust!", name)
}

#[tauri::command]
fn set_window_theme(app_handle: tauri::AppHandle, theme: String) {
    let window = app_handle.get_webview_window("main").unwrap();

    if theme == "dark" {
        window.set_decorations(true).unwrap();
        window.set_theme(Some(tauri::Theme::Dark)).unwrap();
    } else {
        window.set_decorations(true).unwrap();
        window.set_theme(Some(tauri::Theme::Light)).unwrap();
    }
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    // 1. Initial System Migration
    let mut migrations = vec![
        tauri_plugin_sql::Migration {
            version: 1,
            description: "system_init",
            sql: "CREATE TABLE IF NOT EXISTS app_system_info (key TEXT PRIMARY KEY, value TEXT);",
            kind: tauri_plugin_sql::MigrationKind::Up,
        },
    ];

    // 2. Append Drizzle migrations with the +1 offset
    for mut m in get_migrations() {
        m.version += 1; 
        migrations.push(m);
    }

    tauri::Builder::default()
        .plugin(
            tauri_plugin_sql::Builder::default()
                .add_migrations("sqlite:local.db", migrations)
                .build(),
        )
        .plugin(tauri_plugin_opener::init())
        .plugin(tauri_plugin_notification::init())
        .plugin(tauri_plugin_os::init())
        .plugin(tauri_plugin_process::init())
        .plugin(tauri_plugin_updater::Builder::new().build())
        .plugin(tauri_plugin_store::Builder::default().build())
        .setup(|app| {
            let app_data_dir = app.path().app_data_dir().expect("failed to get app data dir");
            
            if !app_data_dir.exists() {
                std::fs::create_dir_all(&app_data_dir).expect("failed to create app data dir");
            }

            let db_path = app_data_dir.join("local.db");

            // Create the SqlitePool for the sync engine (same database file)
            let db_url = format!("sqlite:{}", db_path.to_str().unwrap());
            let db_pool = tauri::async_runtime::block_on(SqlitePool::connect(&db_url))
                .expect("Failed to create SQLite pool for sync engine");

            // List of tables to sync (adjust to your actual tables)
            let tables = vec![
                "tenants".to_string(),
                "customers".to_string(),
            ];

            let api_url = "https://api.famkonect.com/api/v1".to_string(); // change to your server URL
            let engine = SyncEngine::new(db_pool, api_url, tables);
            let engine_state = SyncEngineState(Arc::new(Mutex::new(engine)));
            app.manage(engine_state);

            let window = app.get_webview_window("main").unwrap();
            window.set_theme(Some(tauri::Theme::Light)).unwrap();

            Ok(())
        })
        .invoke_handler(tauri::generate_handler![
            greet, 
            set_window_theme, 
            get_machine_hash,
            store_secure,
            get_secure,
            delete_secure,
            sync_all,
            sync_table,
            get_unsynced_counts])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}